# syntax = docker/dockerfile:1

# pnpm workspaceを最大限活用するため、Dockerfileはルートに設置する
ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# packageManagerを参照できるためcorepackを使用
RUN corepack enable
RUN pnpm config set store-dir ~/.pnpm-store
RUN pnpm add -g turbo

# --------------------------------
# turborepoにより/outディレクトリを生成する
# https://fintlabs.medium.com/optimized-multi-stage-docker-builds-with-turborepo-and-pnpm-for-nodejs-microservices-in-a-monorepo-c686fdcf051f
FROM base AS pruner
WORKDIR /app
COPY . .
RUN turbo prune --scope=bot --docker

# --------------------------------
FROM base AS builder
WORKDIR /app

COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=pruner /app/out/json/ .

RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm install --frozen-lockfile --ignore-scripts

# ソースコードコピー
COPY --from=pruner /app/out/full/ .

RUN turbo build --filter=bot
RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm prune --prod --no-optional
RUN rm -rf ./**/*/src

# --------------------------------
FROM node:${NODE_VERSION}-alpine AS runner
WORKDIR /app

COPY --from=builder --chown=node:node /app .
WORKDIR /app/apps/bot

USER node

ENV NODE_ENV=production
EXPOSE 3000

CMD ["dist/main"]
