# syntax = docker/dockerfile:1

# pnpm workspaceを最大限活用するため、Dockerfileはルートに設置する
ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# packageManagerを参照できるためcorepackを使用
RUN corepack enable
RUN pnpm config set store-dir ~/.pnpm-store
RUN pnpm add -g turbo

WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile --ignore-scripts

WORKDIR /app/apps/bot

USER node

ENV NODE_ENV=testing
EXPOSE 3000
# CMDはdocker-compose.ymlで指定
