name: "stagingへのpush: デプロイ [bot]"

concurrency:
  group: bot-staging
  cancel-in-progress: true
on:
  push:
    branches:
      - staging
    paths:
      - .github/workflows/deploy-bot-staging.yml
      - apps/bot/**

jobs:
  deploy:
    name: botのデプロイ
    uses: ./.github/workflows/reusable-deploy-bot.yml
    with:
      environment: "staging"
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
